-- PostgreSQL Database Schema
-- This file contains all table creation statements extracted from the backup

-- ============================================
-- DROP EXISTING TABLES AND TYPES
-- ============================================

-- Drop tables (in reverse dependency order)
DROP TABLE IF EXISTS public.chat_messages CASCADE;
DROP TABLE IF EXISTS public.chats CASCADE;
DROP TABLE IF EXISTS public.matches CASCADE;
DROP TABLE IF EXISTS public.tickets CASCADE;
DROP TABLE IF EXISTS public.favorites CASCADE;
DROP TABLE IF EXISTS public.event_pictures CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.venue_pictures CASCADE;
DROP TABLE IF EXISTS public.venues CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.hosts CASCADE;
DROP TABLE IF EXISTS public.guests CASCADE;
DROP TABLE IF EXISTS public.balances CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- Drop types
DROP TYPE IF EXISTS public.venue_type_enum CASCADE;
DROP TYPE IF EXISTS public.transaction_status_enum CASCADE;
DROP TYPE IF EXISTS public.transaction_mode_enum CASCADE;
DROP TYPE IF EXISTS public.theme_enum CASCADE;
DROP TYPE IF EXISTS public.ticket_status_enum CASCADE;
DROP TYPE IF EXISTS public.seeking_enum CASCADE;
DROP TYPE IF EXISTS public.language_enum CASCADE;
DROP TYPE IF EXISTS public.gender_enum CASCADE;
DROP TYPE IF EXISTS public.event_status_enum CASCADE;

-- ============================================
-- CUSTOM TYPES (ENUMS)
-- ============================================

CREATE TYPE public.event_status_enum AS ENUM (
    'draft',
    'active',
    'cancelled'
);

CREATE TYPE public.gender_enum AS ENUM (
    'male',
    'female',
    'other'
);

CREATE TYPE public.language_enum AS ENUM (
    'EN',
    'SR',
    'RU'
);

CREATE TYPE public.seeking_enum AS ENUM (
    'casual',
    'relationship',
    'friendship',
    'party'
);

CREATE TYPE public.theme_enum AS ENUM (
    'dark',
    'light',
    'system'
);

CREATE TYPE public.transaction_mode_enum AS ENUM (
    'transfer',
    'purchase'
);

CREATE TYPE public.transaction_status_enum AS ENUM (
    'pending',
    'completed',
    'failed'
);

CREATE TYPE public.venue_type_enum AS ENUM (
    'restaurant',
    'club',
    'bar',
    'cafe',
    'raft'
);

-- ============================================
-- TABLES
-- ============================================

-- Users table (base user information)
CREATE TABLE public.users (
    id text NOT NULL,
    email text NOT NULL,
    username text,
    first_name text,
    last_name text,
    avatar_url text,
    push_token text,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

-- Balances table
-- CREATE TABLE public.balances (
--     id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     amount double precision NOT NULL,
--     user_id text NOT NULL,
--     created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
--     updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
--     CONSTRAINT balances_pkey PRIMARY KEY (id),
--     CONSTRAINT balances_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
-- );

-- Guests table (extends users)
CREATE TABLE public.guests (
    user_id text NOT NULL,
    gender public.gender_enum,
    seeking public.seeking_enum,
    interested_in public.gender_enum[] NOT NULL,
    interests text[] DEFAULT '{}' NOT NULL,
    picture_urls text[] DEFAULT '{}' NOT NULL,
    birthday timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT guests_pkey PRIMARY KEY (user_id),
    CONSTRAINT guests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

-- Hosts table (extends users)
CREATE TABLE public.hosts (
    user_id text NOT NULL,
    CONSTRAINT hosts_pkey PRIMARY KEY (user_id),
    CONSTRAINT hosts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

-- Settings table
CREATE TABLE public.settings (
    user_id text NOT NULL,
    language public.language_enum NOT NULL,
    theme public.theme_enum NOT NULL,
    CONSTRAINT settings_pkey PRIMARY KEY (user_id),
    CONSTRAINT settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- Venues table
CREATE TABLE public.venues (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    host_id text NOT NULL,
    venue_type public.venue_type_enum NOT NULL,
    name text NOT NULL,
    description text,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    address text NOT NULL,
    picture_urls text[] DEFAULT '{}' NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT venues_pkey PRIMARY KEY (id),
    CONSTRAINT venues_host_id_fkey FOREIGN KEY (host_id) REFERENCES public.hosts(user_id)
);

-- Events table
CREATE TABLE public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    venue_id bigint NOT NULL,
    title text NOT NULL,
    description text NOT NULL,
    -- price double precision NOT NULL,
    start_date_time timestamp without time zone NOT NULL,
    end_date_time timestamp without time zone NOT NULL,
    tags text[] NOT NULL,
    -- benefits text[] NOT NULL,
    picture_urls text[] DEFAULT '{}' NOT NULL,
    status public.event_status_enum NOT NULL,
    capacity integer NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT events_pkey PRIMARY KEY (id),
    CONSTRAINT events_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id) ON DELETE CASCADE
);

-- Favorites table
CREATE TABLE public.favorites (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id text NOT NULL,
    event_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT favorites_pkey PRIMARY KEY (id),
    CONSTRAINT favorites_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
    CONSTRAINT favorites_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);

-- Tickets table
CREATE TABLE public.tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id bigint NOT NULL,
    guest_id text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT tickets_pkey PRIMARY KEY (id),
    CONSTRAINT tickets_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT tickets_guest_id_fkey FOREIGN KEY (guest_id) REFERENCES public.guests(user_id) ON DELETE CASCADE
);

-- Matches table (tracks guest matches at events)
CREATE TABLE public.matches (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    guest_id_1 text NOT NULL,
    guest_id_2 text NOT NULL,
    event_id bigint NOT NULL,
    matched_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT matches_pkey PRIMARY KEY (id),
    CONSTRAINT matches_guest_id_1_fkey FOREIGN KEY (guest_id_1) REFERENCES public.guests(user_id) ON DELETE CASCADE,
    CONSTRAINT matches_guest_id_2_fkey FOREIGN KEY (guest_id_2) REFERENCES public.guests(user_id) ON DELETE CASCADE,
    CONSTRAINT matches_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT matches_different_guests CHECK (guest_id_1 <> guest_id_2),
    CONSTRAINT matches_unique_pair UNIQUE (guest_id_1, guest_id_2, event_id)
);

-- Chats table (chat sessions for matched guests)
CREATE TABLE public.chats (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_id bigint NOT NULL,
    event_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chats_pkey PRIMARY KEY (id),
    CONSTRAINT chats_match_id_fkey FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE,
    CONSTRAINT chats_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id) ON DELETE CASCADE,
    CONSTRAINT chats_unique_match UNIQUE (match_id)
);

-- Chat messages table (individual messages in chats)
CREATE TABLE public.chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat_id bigint NOT NULL,
    sender_id text NOT NULL,
    message text NOT NULL,
    is_read boolean DEFAULT false NOT NULL,
    sent_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
    CONSTRAINT chat_messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id) ON DELETE CASCADE,
    CONSTRAINT chat_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.guests(user_id) ON DELETE CASCADE
);

-- Reviews table
-- CREATE TABLE public.reviews (
--     id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     guest_id text NOT NULL,
--     venue_id bigint NOT NULL,
--     comment text NOT NULL,
--     rating double precision NOT NULL,
--     created_at timestamp without time zone NOT NULL,
--     CONSTRAINT reviews_pkey PRIMARY KEY (id),
--     CONSTRAINT reviews_guest_id_fkey FOREIGN KEY (guest_id) REFERENCES public.guests(user_id),
--     CONSTRAINT reviews_venue_id_fkey FOREIGN KEY (venue_id) REFERENCES public.venues(id)
-- );

-- Transactions table
-- CREATE TABLE public.transactions (
--     id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     sender_id text NOT NULL,
--     receiver_id text NOT NULL,
--     amount double precision NOT NULL,
--     status public.transaction_status_enum NOT NULL,
--     mode public.transaction_mode_enum NOT NULL,
--     created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
--     updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
--     CONSTRAINT transactions_pkey PRIMARY KEY (id),
--     CONSTRAINT transactions_receiver_id_fkey FOREIGN KEY (receiver_id) REFERENCES public.users(id),
--     CONSTRAINT transactions_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
-- );

-- Notifications table
-- CREATE TABLE public.notifications (
--     id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     user_id text NOT NULL,
--     body text NOT NULL,
--     card_id bigint,
--     created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
--     CONSTRAINT notifications_pkey PRIMARY KEY (id),
--     CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
-- );

-- ============================================
-- COMMENTS
-- ============================================

COMMENT ON TABLE public.users IS 'Base user information table';
COMMENT ON TABLE public.guests IS 'Guest user profiles extending users table';
COMMENT ON TABLE public.hosts IS 'Host user profiles extending users table';
-- COMMENT ON TABLE public.balances IS 'User balance tracking for transactions';
COMMENT ON TABLE public.venues IS 'Venue information managed by hosts';
COMMENT ON TABLE public.events IS 'Events hosted at venues';
COMMENT ON TABLE public.tickets IS 'Event tickets purchased by guests';
COMMENT ON TABLE public.matches IS 'Guest matches made at events';
COMMENT ON TABLE public.chats IS 'Chat sessions between matched guests';
COMMENT ON TABLE public.chat_messages IS 'Individual messages in chat sessions';
-- COMMENT ON TABLE public.reviews IS 'Guest reviews for venues';
-- COMMENT ON TABLE public.transactions IS 'Financial transactions between users';
COMMENT ON TABLE public.favorites IS 'User favorite events';
